@localhost = http://localhost:8000

### ROUTE TESTS
GET {{localhost}} HTTP/1.1

###
GET {{localhost}}/docs  HTTP/1.1


### Product All api external
GET {{localhost}}/clientes HTTP/1.1

### ITEM
POST {{localhost}}/clientes/1/favoritos HTTP/1.1
content-type: application/json

{
  "cliente_id": 1,
  "produto_id": 123
}


#### Externos Products
GET https://fakestoreapi.com/products HTTP/1.1
content-type: application/json