services:
  
  db:
    image: postgres:15
    container_name: db_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aiQFome
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    depends_on:
      - db
      - cache
    env_file:
      - ./infra/.env.container
    restart: always
    deploy:
      replicas: 2 # Defina o número de instâncias, Design System - LOAD BALANCER
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: always

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  pgdata:
