services:
  api:
    build: .
    container_name: rest_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.container
    restart: always
    # Aguardar o start de DB
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    container_name: db_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aiQFome
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: 
