@localhost = http://localhost:8000/

###
GET {{localhost}} HTTP/1.1

###

GET {{localhost}}itens HTTP/1.1

###

POST {{localhost}}/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}